Add development features
jixxed/StationeersMods pull request #12
Opened 2024-01-02 15:14 UTC by MadrMan

- A new menu in the export settings screen where you can enable/disable development mode. Enabling this lets you attach to the game with the Unity debugger and allows you to debug your code.
- A fields to enter your game folder + arguments, which allows you to do a save & export & run in one click, which saves a lot of time.
- Added an option in the "StationeersMods" menu in Unity to directly use the export and/or run functions without having to go through the settings screen.

Also removed GetShortString() from the export directory text field. Previously it would not allow you to edit or copy from the field directly which kept throwing me off.

2024-01-02 16:57 UTC, jixxed commented on README.md
> +### Debugging
this is out of scope for the main readme. Best to place this in a dedicated doc/DEBUGGING.md

2024-01-02 17:13 UTC, MadrMan commented on README.md
> +### Debugging
That does seem like a better place yea, I've moved that bit to doc/DEBUGGING.md. The only downside is that there don't seem to be any links to any of the files in doc from the main document so they're all a bit hard to find now imo.

2024-01-02 17:19 UTC, jixxed commented on README.md
> +### Debugging
The main one should even be slimmed down further and be more end-user focused. More of an how to install guide.
Mod developers need to start out in the doc directory anyways for the tutorials and templates. There can be references in those docs if it is deemed beneficial. A nice up2date video tutorial will benefit the project the most.

2024-01-20 18:12 UTC, jixxed requested changes

2024-01-20 18:12 UTC, jixxed commented on doc/DEBUGGING.md
> +- When debugging, you should now be able to step through and see any Stationeers code.
Need to expand this a bit with how to do it. For Rider it is:
After starting the game
Run > Attach to Unity Process... > WindowsPlayer <no name>

It would be nice if I can directly debug from Rider, ie. launch game and auto attach. have not figured out how. might miss the breakpoint otherwise.

There is also the option to run a symbol server. could that save a step?

2024-01-20 20:24 UTC, MadrMan commented on StationieersMods/StationeersMods.Editor/DevelopmentEditor.cs
> +                EditorGUILayout.HelpBox("Debug information needs to be exported or it will not be possible to debug your code. Enable Export Settings > Export > Include PDBs.", MessageType.Error, tru
> The path here is incorrect `Enable Export Settings > Export > Include PDBs` I think this should be a warning level and moved to the export page. Only show the warning when development mode=true and Include PDBs=false. The warning can then read: "Include PDBs not checked while in development mode. Make sure to check Include PDBs if you want to be able to debug the code."

I've fixed the path, but I feel the warning in the right spot. It's important enough that it should always be visible when on the Development tab (since the only point of enabling it as far as I know is so you can debug). Also, users might not visit the export page after enabling development mode since you can now export and run through the menu directly.



> We can also add a link here to where the documentation will be: https://github.com/jixxed/StationeersMods/tree/main/doc/DEBUGGING.md with title "How to debug"

I've added this link in the helpbox.

2024-01-20 20:25 UTC, MadrMan commented on doc/DEBUGGING.md
> +- Copy the following files from `C:\Program Files\Unity 2021.2.13f1\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win64_player_development_mono`:
Changed it to [Unity installation folder]

2024-01-20 20:25 UTC, MadrMan commented on doc/DEBUGGING.md
> +The first step is to set Stationeers to development mode. The easiest way to do this is to use the StationeersMods menu in Unity to enable development mode automatically. The steps to do it manually
I've clarified the text a bit.

2024-01-20 20:25 UTC, MadrMan commented on doc/DEBUGGING.md
> +- Install dotPeek and load up `Assembly-CSharp.dll`. After it loads, right-click Assembly-CSharp in the Assembly Exporer and select "Generate Pdb...". Export anywhere.
Added

2024-01-20 20:33 UTC, MadrMan commented on doc/DEBUGGING.md
> +- When debugging, you should now be able to step through and see any Stationeers code.
I added a link to the Unity documentation explaining how to set up various IDEs.

I don't think the symbol server works, VSTU at least doesn't seem to understand it - I haven't used the Rider version.

It should be possible to add a post-build command in VS at least if you check the override option, haven't looked into it much. It's not super well supported for unity I think.

2024-01-21 08:17 UTC, merged